### ISSUE TITLE
Mass deployment fails

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1699]
### Description

The results of mass deployment runs are inconsistent; they sometimes pass and sometimes fail.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/mass_deployments.yml

**Comment by zaelgohary** [comment]
Blocked on readiness for deployment on the mainnet.

**Comment by zaelgohary** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1765

**Comment by zaelgohary** [comment]
Investigation: 
Sometimes script fails because of 'NodeCrypto_DecryptionFailure'. Still looking into it.

**Comment by zaelgohary** [comment]
Couldn't reproduce. Will move to verification.

**Comment by A-Harby** [comment]
But it happened more than once in the past few days.
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7375436687
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7368827180
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7362509843

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Still trying to reproduce the `NodeCrypto_DecryptionFailure` issue locally however there's still no luck and i wasn't able to reproduce it and thus still don't know which node/s does this issue originate from.

**Comment by mohamedamer453** [comment]
Update:

Investigation:

I've tried to ping all nodes on mainnet and again i wasn't able to reproduce the `NodeCrypto_DecryptionFailure` error. and [here](https://gist.github.com/mohamedamer453/71b376191ca04fddefde5e919453fdeb) are the full logs of pinging mainnet nodes.

Will move this issue to verification since it wasn't reproducible either by running the mass deployments script locally or by manually pinging all nodes on mainnet.

**Comment by A-Harby** [comment]
Some of the workflows are still failing, but they show a newer error than before.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7580225420/job/20645700661
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7566134358/job/20603017257
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7598022973/job/20693545536

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/28f7d2e0-fee6-4f98-b4e1-eb481e127aa1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e7262b0-b275-49aa-b9fe-c73e766c83ca)

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Just picked up the issue, still trying to figure out what's going on from the logs of the latest runs, the only thing weird that's in common with failed runs is that they take almost 6 hours till they fail.

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Still trying to figure out what's the issue, i've found the step where the workflow keeps getting stuck at as seen in the previous runs.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7630102061/job/20785028492#step:6:7043
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7619559607/job/20752840009#step:6:3875
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7627849288/job/20777503003#step:6:4477
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7627554421/job/20776515897#step:6:4856

```
2024-01-23 15:05:17        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-01-23 15:05:18        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
```

**Comment by mohamedamer453** [comment]
Update:

Issue is blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2073 since the issue seems to be originating from the grid client not the workflow itself.

**Comment by mohamedamer453** [comment]
Should be fixed since https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2106 was merged.
