### ISSUE TITLE
Presearch: Deployed instances are not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#268]
### Description

Presearch deployments are not working and don't appear in the presearch dashboard after deployment.

I think it might be related to resources since the rootfs is set to 0 in the deployment as mentioned before in threefoldtech/tfgrid-sdk-ts#269 

from the machine itself the rootfs is not listed.

![image](https://github.com/threefoldtech/playground/assets/101194226/663b37ce-66f6-4d1b-91f0-34a92fd1bf86)

and from the deployment details it's 0

![image](https://github.com/threefoldtech/playground/assets/101194226/a4194fb8-da19-4199-be82-9eedc8c2919f)

and after executing `zinit list` in the machine the following errors were returned for the prenode and the preupdater services.

![image](https://github.com/threefoldtech/playground/assets/101194226/f7b7ec89-98c5-4628-8dcb-e06c4a7c75f2)

Full logs from `zinit log` can be found [here](https://gist.github.com/mohamedamer453/2f38136694125cfb16ad9459eba0e154).

**Comment by 0oM4R** [comment]
deployed an instance without public ip and i got the same issue, but i deployed another instance with public ip and it appeared in the presearch dashboard after the deployment, i think we are missing the presearch node filtring.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0272e9d0-6f4c-4aff-ab48-6c66d62b062b)

`````
[
  {
    "version": 0,
    "contractId": 27702,
    "nodeId": 11,
    "name": "PS2TE8KgpQ",
    "created": 1685024171,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-apps/presearch-v2.2.flist",
    "publicIP": {
      "ip": "185.206.122.20/24",
      "ip6": "",
      "gateway": "185.206.122.1"
    },
    "planetary": "302:9e63:7d43:b742:474d:712b:4341:24b5",
    "interfaces": [
      {
        "network": "NWD39chmLYsA",
        "ip": "10.20.2.2"
      }
    ],
    "capacity": {
      "cpu": 4,
      "memory": 8192
    },
    "mounts": [],
    "env": {
      "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKkaopr/tRilmLprntgqAO6JxnhzhrrB02KeUsNys9qj/G4RtXK4hKZo3yj42Kuoub53TxoW/BfZSRUbY0VNUgZSsifCyDE4g1UXi83ic+uepPb1VIfzlFdtZPUo/dEtjfS5FM7GVAPZCDik08w2+uXeZiAKavLTDQFh2cuIqE5QnQ44enODTMkSDPVJSKJ6NSoNcrY2I++AtcxgNFzy/7YWoT/bA19CliGqxBMSQ/GjOEAF3iQjUPc5LYcqCYAc0Y6WPt2l8uEVvhJAtsLelGApt8v/Nq/OBEKJpUQB2cfkyKlwLLphKFtQ8gcKjrbpE47lVsfbW68uqCw/5avA71HlS6AXxMeda8GZ99UqDTOLoUbd+EEo17hiHs6Nvle8DHNfWdGT2wx+DhzZeCO719UadmQxFLYDd75dDH5gLkMxr9JXPWDqdxvsyMZilxZPk3UQbK811obYSMrc9L+u8vwLs0weUBxnygutnU0eF9cRQxFgx3zOOfwI1ugI9SgSU= omarkassem099@gmail.com",
      "PRESEARCH_REGISTRATION_CODE": "bff768537bd813ac7ac159c968a29a3f",
      "PRESEARCH_BACKUP_PRI_KEY": "",
      "PRESEARCH_BACKUP_PUB_KEY": ""
    },
    "entrypoint": "/sbin/zinit init",
    "metadata": "{\"type\":\"vm\",\"name\":\"PS2TE8KgpQ\",\"projectName\":\"presearch\"}",
    "description": "",
    "rootfs_size": 0,
    "corex": false,
    "deploymentName": "PS2TE8KgpQ",
    "projectName": "presearch",
    "billing": "No Data Available"
  }
]
`````

**Comment by 0oM4R** [comment]
Update: 
worked with Rabie on it, the playground miss the research filtring logic, 
Rabie implemented the logic on https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development_fix_presearch .
will verify the logic and the filtering constraints

**Comment by 0oM4R** [comment]
Status: pr #389  ready for review

**Comment by A-Harby** [comment]
Error still happens with presearch tih IPV4

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cb36dff0-e2da-40e2-9b94-c32aac47f6eb)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/875301ac-7480-453c-8d76-a7d6636c341c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bc511b63-84df-4e0f-a0f6-919af36c2305)

while the one with no ipv4 is working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/152725b1-9b2f-4e69-805a-499cb5c9faad)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/07fe3532-a072-4744-8431-6a5fa62a8c1e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1abff876-a473-46a9-bd68-43b996881d6a)

**Comment by 0oM4R** [comment]
@A-Harby  can you provide the full deployment data?

**Comment by A-Harby** [comment]
Playground Devnet, e491a60.
Unfortunately I had to delete that instance but I tried to deploy other presearch instances to reproduce the error but all of them were working fine, them to be solved for now.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3ed692b2-a558-414f-9670-896bdc9c3d9e)

Will try deploying more if the error occurred will re-open the issue.
