### ISSUE TITLE
Improve handling of NodeNotAvailableToDeploy error

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#3332]
When tfchain returns `NodeNotAvailableToDeploy` error when attempting to create a contract, the user is presented with a pretty unhelpful dump. For example:

![image](https://github.com/user-attachments/assets/6ef38a1e-6b8f-4c09-a9b9-57e91cf76ae5)

There are four cases where this error is fired:

1. Node is standby and user tries to deploy a shared workload
2. Node is "dedicated" (has an additional fee set) and user tries to deploy a shared workload
3. Someone else has rented the node and user tries to deploy a shared workload
4. Someone else has rented the node and the user tries to rent the node as dedicated

I think the UI should be able to prevent the user from attempting these actions in the first place. Specifically I noticed that case 2 is possible in the dashboard right now.

So I'd like to see two things:

- [ ] Validation that the node is eligible to deploy to/rent in all cases mentioned above. Stop the user if not
- [ ] In case the error happens to fire anyway, print a message that explains the possible cases. Send the error dump to the logs instead

**Comment by 0oM4R** [comment]
Issue updated:
- handled first two cases.
**but we have this `UnavailableNodeError` not the `NodeNotAvailableToDeploy`**

- the third case is already handled: `Someone else has rented the node and user tries to deploy a shared workload`
   ![Image](https://github.com/user-attachments/assets/5f0ae06e-909a-4af1-b2e5-43beb27a7058)


- the fourth one is not clear `Someone else has rented the node and the user tries to rent the node as dedicated`
the reserve button is hidden if the node is rented.

@scottyeager can you confirm the error and explain the fourth case ?

**Comment by scottyeager** [comment]
Hi @0oM4R,

I was listing all four cases whereby tfchain might return the `NodeNotAvailableToDeploy` error, just to be sure we considered them all. Seems `sdk-ts` doesn't mirror the error types from tfchain which is okay.

Regarding case four, I see what you mean. Again, I was just enumerating all possible cases from the perspective of tfchain. What I was suggesting overall though is that even if these actions should be blocked by the UI, it might still be possible that some corner case or regression results in the user encountering the error anyway. 

So that's why I was suggesting to catch this error and print a more human readable message, but I think it's good enough if we can just prevent the user from trying these action in the UI under normal circumstances.

**Comment by 0oM4R** [comment]
@scottyeager Can you please mention the network that you faced `NodeNotAvailableToDeploy`, and did you use the automated node finder or manual filter?
if you have any additional details about the case that caused that error please mention it.
I want to reproduce the error on the provided screenshot, in the sdk-ts all mentioned cases are already handled to throw `UnavailableNodeError` so i want to know where does it comes form~

**Comment by 0oM4R** [comment]
@scottyeager any update?

**Comment by 0oM4R** [comment]
will move this to verification as the fix is addressed on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3769 
#3730

**Comment by khaledyoussef24** [comment]
could not produce the same issue
but also verified the new behaviour if the user inserted a rented node by some one else : 

![Image](https://github.com/user-attachments/assets/99457946-9d10-4b3c-bebe-e31bec5282c0)

node is down : 
![Image](https://github.com/user-attachments/assets/480b4988-dbc7-4cc5-b127-4f25a6acd889)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4164692)

will test again in testnet and address the issue in the testcase ( for standby case and the rented error case)

**Comment by ramezsaeed** [comment]
Verified also for standby node
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3730#issuecomment-2571538002

**Comment by scottyeager** [comment]
> 2\. Node is "dedicated" (has an additional fee set) and user tries to deploy a shared workload

Reopening because case 2 is still not handled well. When a node has an extra fee set, the dashboard allows me to attempt a VM deployment even though it's recognized as "Dedicated":

<img width="1598" height="678" alt="Image" src="https://github.com/user-attachments/assets/eae16f35-e653-4fec-8740-1f6b8a07eaf0" />

Then it ends up with this error (which doesn't seem to contain any info about the actual issue):

<img width="1523" height="273" alt="Image" src="https://github.com/user-attachments/assets/31c5cb23-6dd5-4a37-910b-66562457cfce" />

You can reproduce this by trying to deploy a micro VM on node 6310.
