### ISSUE TITLE
list dedicated nodes in the capacity filter

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#757]
as a user i may have rented a node on farm X, and while deploying on farm X, there's no way to specify if i want to deploy on a shared node or a dedicated node (from what i understood from devs, dedicated nodes get priority)

I don't think there's an option, but to restore the node selector or listing the dedicated nodes in a farm to choose from.

**Comment by Mahmoud-Emad** [comment]
Searching with @ehab-hassan for the best flow

**Comment by ehab-hassan** [comment]
What about adding a switch to show a shared node, but that'll be clickable when the user already had a shared node?
![Frame 60](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/0189aa36-0cc0-438a-baba-18ae3648d3ef)

**Comment by xmonader** [comment]
the user reserves a dedicated node, not a shared node

**Comment by zaelgohary** [comment]
Edited the filters in select farm to include dedicated but it's not working although I have rented a dedicated node. I tried to use farmerbot script from the client and it returns no available nodes.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/ab42d9a7-aeff-48c9-9b68-f4609d387a52)


![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/5bc1a26f-50cd-4f2b-82dc-7bff09aae82a)

will continue working on it tomorrow.

**Comment by zaelgohary** [comment]
In order for Farmerbot to be able to find a node, the node configuration file needs to be updated with the certified & dedicated nodes manually. An [issue](https://github.com/threefoldtech/farmerbot/issues/53) was opened to change this flow. The PR will be ready for review once the issue is closed.

**Comment by zaelgohary** [comment]
Used Grid Proxy to list dedicated nodes in Playground instead of Farmerbot.

**Comment by zaelgohary** [comment]
Dedicated nodes are now listed in Fullvm, Microvm & Freeflow. I'm working on adding them to the other solutions.

**Comment by zaelgohary** [comment]
Refactored select node to include all nodes (dedicated & shared). Also added a chip beside each node so it would be easily labeled. Added the changes in fullvm & micro.

**Comment by zaelgohary** [comment]
Select nodes are now implemented in all solutions except for Caprover & K8s.

**Comment by zaelgohary** [comment]
All solutions have select node component.

**Comment by mohamedamer453** [comment]
- Changing the resources after loading the nodes will always return no nodes rented by you with these resources even when the resources are lower than the previously searched with.

[Untitled_ Jul 26, 2023 12_51 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c72ac5b9-6815-4319-9d81-d65920150e73)


- Selecting a farm and then switching to another one before the nodes load will display the nodes of the first farm and sometimes it displays the nodes of both farms.

[Untitled_ Jul 26, 2023 12_57 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0997b84e-62bd-4098-8f6e-fb45df72a1fc)

**Comment by mohamedamer453** [comment]
Also the message that appears when the resources are not found mentions that there are no nodes rented by you that match these resources, even when the `Dedicated` switch is disabled.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/7a6f935d-a57f-4aa7-b8d1-390146346280)

I think that this message should appear when there are no nodes with these resources found but when the `Dedicated` switch is enabled. and another message should appear when it's disabled and there are no resources mentioning that there are no nodes that match the selected resources without mentioning anything about rented nodes.

**Comment by mohamedamer453** [comment]
Another issue is when the user interrupts the loading of the nodes by enabling the `Dedicated` or `Certified` filters, it will firstly show that there are no nodes available but eventually when the request of loading the nodes is done then it will display the nodes from the first request with the `Dedicated` or `Certified` filters enabled.

- Dedicated

[Untitled_ Jul 26, 2023 1_29 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/17cc86b7-063c-4d72-ac95-428086bd01b1)


- Certified

[Untitled_ Jul 26, 2023 1_30 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4bc6468d-2a66-4202-855b-f3c62496e3c7)

**Comment by 0oM4R** [comment]
> * Selecting a farm and then switching to another one before the nodes load will display the nodes of the first farm and sometimes it displays the nodes of both farms.

should be fixed in #853

**Comment by mohamedamer453** [comment]
> * Changing the resources after loading the nodes will always return no nodes rented by you with these resources even when the resources are lower than the previously searched with.
> 
> * Selecting a farm and then switching to another one before the nodes load will display the nodes of the first farm and sometimes it displays the nodes of both farms.

both of these issues were fixed and now it returns nodes normally when you change the resources and the country/farm filters are now disabled when it's searching for a node.

[TF Playground _ Full Virtual Machine (5).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2a43fc8b-1be8-4599-99a3-7eb0a6696533)

**Comment by mohamedamer453** [comment]
> I think that this message should appear when there are no nodes with these resources found but when the `Dedicated` switch is enabled. and another message should appear when it's disabled and there are no resources mentioning that there are no nodes that match the selected resources without mentioning anything about rented nodes.

When the dedicated node switch is not enabled it just says that no farms were found.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/de92d719-9fdb-4d68-b335-c716897761ea)

However when it's enabled it shows the same error message in the farms field but in the node field it doesn't show any error and it returns nodes in it.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/aab3c54a-f0d1-40a1-8b9d-29dcb1991aa0)


> Another issue is when the user interrupts the loading of the nodes by enabling the `Dedicated` or `Certified` filters, it will firstly show that there are no nodes available but eventually when the request of loading the nodes is done then it will display the nodes from the first request with the `Dedicated` or `Certified` filters enabled.

This issue is still present.

[TF Playground _ Full Virtual Machine (6).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/14bee55c-0695-44c9-ac83-daddf8c7aac9)

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now the nodes don't load when interrupted with the dedicated or certified filters.

[TF Playground _ Full Virtual Machine (8).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5abaa352-5016-4e04-a5d6-2c76ff1fa4b7)

> When the dedicated node switch is not enabled it just says that no farms were found.

this issue is still reproducible under certain conditions so i created a separate issue for it. https://github.com/threefoldtech/tfgrid-sdk-ts/issues/887
